name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t europe-west1-docker.pkg.dev/prova-holded-id/prova-holded-repo/golang-server:latest .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: docker run --rm europe-west1-docker.pkg.dev/prova-holded-id/prova-holded-repo/golang-server:latest go test ./...

  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: europe-west1-docker.pkg.dev/prova-holded-id/prova-holded-repo/golang-server:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: prova-holded-id
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials holded-cluster --region europe-west1 --project prova-holded-id
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml
